#!/usr/bin/with-contenv bash

# 
[[ ! -d "/opt/plexpy/.git" ]] && (git clone https://github.com/drzoidberg33/plexpy.git /opt/plexpy && \
chown -R abc:abc /opt/plexpy)


# opt out for autoupdates
[ "$ADVANCED_DISABLEUPDATES" ] && exit 0
cd /opt/plexpy
git pull
chown -R abc:abc /opt/plexpy
